import { std } from "wow/wotlk"

export const CLASH_OF_ELEMENTS = std.Spells
    std.Spells.create('battleroyale', 'clash-of-elements', 44614)
    .Name.enGB.set('Clash of the elements')
    .Description.enGB.set('Unleash the fury of the elements upon your enemies, inflicting $s1 damage. In addition, your foes will suffer from a reduction of $s2 in their resistance to Fire, Frost, Nature, and Arcane spells.')
    .CastTime.setSimple(2000)
    .Duration.setSimple(8000)
    .Range.setSimple(0, 30)
    .Cooldown.set(180000)
    .Effects.clear(0)
    .Effects.clear(1)
    .Effects.clear(2)
    .Tags.addUnique('battleroyale', 'clash-of-elements')
    .Icon.setFullPath('Interface\\Icons\\clash-of-elements')
    .Effects.addMod((eff) => {
        eff
            .Type.APPLY_AURA.set()
            eff.PointsPerLevel.set(1)
            .PointsBase.set(40)
            .PointsDieSides.set(3)
            .ImplicitTargetA.UNIT_TARGET_ENEMY.set()
            .Aura.PERIODIC_DAMAGE.set()
    })
    .Effects.addMod((eff2) => {
        eff2
            .Aura.MOD_BASE_RESISTANCE_PCT.set()
            .ImplicitTargetA.UNIT_TARGET_ENEMY.set()
            .Schools.FROST.set(1)
            .PercentBase.set(31)
            .Schools.NATURE.set(1)
            .PercentBase.set(31)
            .Schools.FIRE.set(1)
            .PercentBase.set(31)
            .Schools.ARCANE.set(1)
            .PercentBase.set(31)
    })

export const HOLY_SPIRIT = std.Spells.create('battleroyale', 'paliauratest')
    .Duration.set(21)
    .Range.setSimple(0, 0)
    .Icon.setFullPath('Interface\\Icons\\ability_evoker_return')
    .ActiveIcon.setFullPath('Interface\\Icons\\ability_evoker_return')
    .Name.enGB.set('Holy Spirit')
    .Subtext.enGB.set('test subtext')
    .Description.enGB.set('description')
    .AuraDescription.enGB.set('this is $s1 damage increase and decreases ranged damage by 1%')
    .Family.set(12)
    .Cooldown.StartCategory.set(133)
    .Power.PowerType.set("MANA")
    .Visual.set(160)
    .Effects.addMod((eff => {
        eff.Type.APPLY_AREA_AURA_RAID.set()
        eff.PointsBase.set(99)
        eff.PointsDieSides.set(1)
        eff.ImplicitTargetA.SRC_CASTER.set()
        eff.Radius.setSimple(40)
        eff.Aura.MOD_DAMAGE_DONE.set()
        eff.MiscValueA.set(1)
        eff.MultipleValue.set(1)
    }))
    .Effects.addMod((eff2 => {
        eff2.Type.APPLY_AREA_AURA_RAID.set()
        eff2.PointsBase.set(99)
        eff2.PointsDieSides.set(1)
        eff2.ImplicitTargetA.SRC_CASTER.set()
        eff2.Radius.setSimple(40)
        eff2.Aura.MOD_RANGED_DAMAGE_TAKEN.set()
        eff2.MiscValueA.set(1)
        eff2.MultipleValue.set(1)
    }))

    .Attributes.CASTABLE_WHILE_MOUNTED.set(1)
    .Attributes.CASTABLE_WHILE_SITTING.set(1)
    .Attributes.DISPLAY_IN_STANCE_BAR.set(1)
    .Attributes.PERSISTS_DEATH.set(1)
    .Attributes.CAN_TARGET_DEAD.set(1)
    .Attributes.USABLE_IN_ARENA.set(1)
    .Attributes.NO_CHECK_CAST_POWER.set(1)
    .Tags.addUnique('battleroyale', 'paliauratest')

export const HEROIC_SACRIFICE = std.Spells.create('battleroyale','heroic-sacrifice')
    .Duration.set(5000)
    .Name.enGB.set('Heroic Sacrifice')
    .Subtext.enGB.set('test subtext')
    .Description.enGB.set('description')
    .AuraDescription.enGB.set('this is $s1 damage increase and decreases ranged damage by 1%')
    .Effects.addMod((eff => {
        eff.Aura.PERIODIC_DAMAGE
        eff.PointsBase.set(9)
        eff.PointsDieSides.set(1)
        eff.ImplicitTargetA.SRC_CASTER.set()
        eff.MiscValueA.set(1)
        eff.MultipleValue.set(1)
    }))
    .Effects.addMod((eff2 => {
        eff2.Aura.PERIODIC_HEAL
        eff2.PointsBase.set(29)
        eff2.PointsDieSides.set(5)
        eff2.ImplicitTargetA.UNIT_NEARBY_RAID.set()
        eff2.Radius.set(60)
        eff2.AuraPeriod.set(2000)
    }))
    .Effects.addGetTriggerSpell('battleroyale','heroic-sacrifice-effect', 4,)
    .Tags.addUnique('battleroyale', 'heroic-sacrifice')

export const VENDETTA = std.Spells.create('battleroyale','vendetta', 53338)
    .Name.enGB.set('Vendetta')
    .Description.enGB.set('This ability marks an enemy target as the rogues primary target and increases the rogues damage dealt to that target for a short period of time.')
    .Duration.set(7000)
    .Power.setEnergy(10,10)
    .Effects.clear(2)
    .Effects.addMod((eff2 => {
        eff2.Aura.MELEE_ATTACK_POWER_ATTACKER_BONUS.set()
        eff2.PointsBase.set(1000)
        eff2.PointsDieSides.set(2)

    }))
    .Tags.addUnique('battleroyale', 'vendetta')

export const CRIMSON_VAIL = std.Spells.create('battleroyale','crimson_vail')
    .Name.enGB.set('Crimson Vail')
    .Description.enGB.set('The rogue can consume a vial of their own blood, instantly restoring a significant amount of health.')
    .Duration.set(4000)
    .Power.setEnergy(20)
    .SchoolMask.set(3)
    .Icon.setFullPath('Interface\\Icons\\crimson-vail')
    .Effects.addMod((eff2 => {
        eff2.Aura.MOD_HEALTH_REGEN_PERCENT
        eff2.PointsBase.set(5)
        eff2.PointsDieSides.set(1)
        .ImplicitTargetA.SRC_CASTER
    }))
    .Tags.addUnique('battleroyale', 'crimson_vail')